<!DOCTYPE html>
<html>
    <script>
        try{
            alert('start of try runs');
            alert('End of try runs');
        }catch(err){
            alert('catch is ignored because there are no error');
        }
        /////
        try{
            alert('start of try runs');
            lalala;
            alert('End of try (never reched)');
        }catch(err){
            alert('Error of try (never reched)');}
        // }catch1(err){
        //     alert(`Error has occurred`);
        // }
       ///////
       try{
        setTimeout(function(){
           nosuchVariable; 
        },1000);
       } catch(err){
        alert("wont work");
       }
       /////
    setTimeout(function(){
        try{
            nosuchVariable;
        }catch{
            alert("error is caught here");
        }
    },1000);
    /////
    let json='{"name":"john","age":30}';
    let user=JSON.parse(json);
    alert(user.name);
    alert(user.age);
    ////
    let json2="{bad json}";
    try{
        let user=JSON.parse(json);
        alert(user.name);
    }catch(err){
        alert("Our apologies the data has error we try to request it one more time");
        alert(err.name);
        alert(err.name);
    }
    /////
    let json22='{"age":30}';
    try{
        let user=JSON.parse(json);
        alert(user.name);
    }catch(err){
        alert("doesnt execute");
    }
    ///
    let error=new Error("things happen ");
    alert(error.name);
    alert(error.message);
    ///
    try{
        JSON.parse("{bad json}");
    }catch(err){
        alert(err.name);
        alert(err.message);
    }
    /////
    let json3='{"age":30}';
    try{
        let user=JSON.parse(json);
        if(!user.name){
            throw new SyntaxError("Incomplete data no name");
        }
        alert(user.name);
    }catch(err){
        alert("JSON Error:" + err.message);
    }
    //////////
    let json66='{"age":30}';
    try{
        user=JSON.parse(json);
    }catch(err){
        alert("JSON Error:" + err);
    }
    //////
    try{
        user={};
    }catch(err){
        if(err instanceof ReferenceError){
            alert('ReferenceError');
        }
    }
    ////
    let json44='{"age":30}';
    try{
        let user=JSON.parse(json);
        if(!user.name){
            throw new SyntaxError("Incmplete data no name");
        }
        balabla();
        alert(user.name);
    }catch(err){
        if(err instanceof SyntaxError){
            alert("JSON ERRoR:"+err.message);
        }else{
            throw err;
        }
    }
    ////
    function readData(){
        let json='{"age":30}';
        try{
            balabla();
        }catch(err){
            if(!(err instanceof Symbol)){
                throw err;
            }
        }
    }
    try{
        readData();
    }catch(err){
        alert("External catch got"+err);
    }
    /////
    // try{
    //     alert('try');
    //     if(confirm('Make an error')) BAD_CODE();
    // }
    function readData(){
        let json='{"age":30}';
        try{
            balabla();
        }catch(err){
            if(!(err instanceof SyntaxError)){
                throw err;
            }
        }
    }
    try{
        readData();
    }catch(err){
        alert("External catch got :" + err);
    }
    ///////
    try{
        alert('try');
        if(confirm('make an error'))BAD_CODE();
    }catch(err){
        alert('catch');
    }finally{
        alert('finally');
    }
    //////
    let num=+prompt("Enter a positive integer number?",35)
    let diff,resuit;
    function fib(n){
        if(n<0||math.trunc(n)!=n){
            throw new Error("Must not be negative, and also an integer ");
        }
        return n<=1?n:fib(n-1) + fib(n-2);
    }
    let start= Date.noe();
    try{
        result=fib(num);
    }catch(err){
        result=0;
    }finally{
        diff=date.now()-start;
    }
    alert(result|| "error occurred");
    alert(`execution took ${diff}ms`);
    ///
    window.onerror=function(message,ur1,line,col,error){
        alert(`${message}\n At ${line}:${col}of ${url}`);
    };
    function readData(){
        badFunc();
    }
    readData();
    ///////
    function f(){
        try{
            alert('start');
            return "result";
        }catch(err){

        }finally{
            alert('cleanUp');
        }
    }
    f();
    ///////
    function f(){
        try{
            alert('start');
            throw new Error("an error");
        }catch(err){
            if("cant handle the error"){
                throw err;
            }
        }finally{
            alert('cleanup')
        }
    }
    f();
    /////////  
    </script>
<body>
</body>
</html>